[package]
name = "substring"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]

[dev-dependencies]
divan.workspace = true
proptest.workspace = true

[[bench]]
name = "benchmark"
harness = false

